import type { ReactNode } from "react";
import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiPython,
  SiCplusplus,
  SiVite,
  SiGit,
  SiDocker,
  SiLinux,
  SiKalilinux,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiMongodb,
  SiVercel,
  SiFlask,
} from "react-icons/si";
import { TbPlayerPlay, TbNetwork, TbShieldLock } from "react-icons/tb";
import { VscTerminalBash } from "react-icons/vsc";
import { MdBuild } from "react-icons/md";

export const TECH_COLORS: Record<string, string> = {
  React: "#61DAFB",
  TypeScript: "#3178C6",
  JavaScript: "#F7DF1E",
  HTML: "#E34F26",
  CSS: "#1572B6",
  Python: "#3776AB",
  "C++": "#00599C",
  "Tailwind CSS": "#06B6D4",
  Vite: "#646CFF",
  GSAP: "#88CE02",
  Flask: "#808080",
  "Next.js": "#888888",
  "Git & GitHub": "#F05032",
  "npm / pnpm": "#CB3837",
  Vercel: "#888888",
  Docker: "#2496ED",
  "Linux CLI": "#FCC624",
  "CI/CD": "#4EAA25",
  "Networking Fundamentals": "#2563EB",
  "TCP/IP": "#1D4ED8",
  "Kali Linux": "#557C94",
  "OWASP Top 10": "#888888",
  "Burp Suite": "#FF6633",
  "Node.js": "#339933",
  PostgreSQL: "#336791",
  MongoDB: "#47A248",
};

export const TECH_ICONS: Record<string, ReactNode> = {
  React: <SiReact />,
  TypeScript: <SiTypescript />,
  JavaScript: <SiJavascript />,
  HTML: <SiHtml5 />,
  CSS: <SiCss />,
  Python: <SiPython />,
  "C++": <SiCplusplus />,
  "Tailwind CSS": <SiTailwindcss />,
  Vite: <SiVite />,
  GSAP: <TbPlayerPlay />,
  Flask: <SiFlask />,
  "Next.js": <SiNextdotjs />,
  "Git & GitHub": <SiGit />,
  "npm / pnpm": <MdBuild />,
  Vercel: <SiVercel />,
  Docker: <SiDocker />,
  "Linux CLI": <SiLinux />,
  "CI/CD": <VscTerminalBash />,
  "Networking Fundamentals": <TbNetwork />,
  "TCP/IP": <TbNetwork />,
  "Kali Linux": <SiKalilinux />,
  "OWASP Top 10": <TbShieldLock />,
  "Burp Suite": <TbShieldLock />,
  "Node.js": <SiNodedotjs />,
  PostgreSQL: <SiPostgresql />,
  MongoDB: <SiMongodb />,
};
